name: test
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: "00 15 * * *" # 7:00 PST (-8), 8:00 PDT (-7)
jobs:
  test:
    runs-on: ubuntu-latest
    container: ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - ruby:2.5
          - ruby:2.6
          - ruby:2.7
          # TODO: add jruby and truffleruby
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.ruby }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
      - run: apt-get update && apt-get install -y nodejs # For execjs
      - name: bundle install
        run: bundle install --path vendor/bundle -j$(nproc) --retry 3
      - run: bundle exec rake test
