name: test
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  test:
    runs-on: ubuntu-latest
    container: ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - ruby:2.5
          - ruby:2.6
          - ruby:2.7
          - ruby:3.0
          # TODO: add jruby and truffleruby
    steps:
      - uses: actions/checkout@v2
      - name: bundle install
        run: bundle install -j$(nproc) --retry 3
      - run: bundle exec rake test
